In [1]:
import numpy as np 
import cv2 

In [3]:
face_cade= cv2.CascadeClassifier('./casscade_clasifier/haarcascade_frontalface_default.xml')

In [4]:
img = cv2.imread('./USman_model_data/usman_img_8.jpg')
img= cv2.resize(img,None,fx=0.2,fy=0.2, interpolation=cv2.INTER_AREA)
cv2.imshow('img',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [5]:
object,num_detection=face_cade.detectMultiScale2(img)

In [8]:
print(object)

[[ 83 250 255 255]]


In [11]:
#draw a rectangle 
pt1= (83,250)
pt2= (83+255,250+255)
cv2.rectangle(img,pt1,pt2,(0,255,0),1)
cv2.imshow('img',img)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [12]:
#to fraw a circle 
cx = 83+255//2
cy = 250+255//2
r= 255//2
cv2.circle(img,(cx,cy),r,(0,0,255),2)
cv2.imshow('ciercle ',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
face_cade= cv2.CascadeClassifier('./casscade_clasifier/haarcascade_frontalface_default.xml')


In [17]:
img1= cv2.imread('./USman_model_data/get_from_internet.jpg')
img1= cv2.resize(img1,None,fx=0.5,fy=0.5)
cv2.imshow('friends',img1)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [19]:
faces,num_detections=face_cade.detectMultiScale2(img1,minNeighbors=10)
print(faces)

[[468 143 115 115]
 [564 173  93  93]
 [227 174 108 108]
 [362 154 108 108]
 [103 191 111 111]]


In [20]:
print(num_detections)

[ 64  51 120 118  60]


In [ ]:
for x,y,w,h in faces:
    cv2.rectangle(img1,(x,y),(x+w,y+h),(0,255,0),2)

cv2.imshow('friends',img1)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [38]:
face_cade= cv2.CascadeClassifier('./casscade_clasifier/haarcascade_frontalface_default.xml')
eye_cade= cv2.CascadeClassifier('./casscade_clasifier/haarcascade_eye.xml')

smile_cascade= cv2.CascadeClassifier('./casscade_clasifier/haarcascade_smile.xml')


In [ ]:
img2= cv2.imread('./USman_model_data/get_from_internet.jpg')
img2= cv2.resize(img2,None,fx=0.5,fy=0.5)
    
# cv2.imshow('friends',img1)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

In [56]:
faces,num_detections=face_cade.detectMultiScale2(img2,minNeighbors=10)


In [57]:
for x,y,w,h in faces:
    face_roi= img2[y:y+h,x:x+w].copy()
    cv2.rectangle(img2,(x,y),(x+w,y+h),(0,255,0),2)

    eyes, num_eyes= eye_cade.detectMultiScale2(face_roi,minNeighbors=4)
    for ex,ey,ew,eh in eyes:
        cx= x+ex+ew//2
        cy= y+ey+eh//2
        r= eh//2
        cv2.circle(img2,(cx,cy),r,(0,0,255),2)
    smile, num_smiles= smile_cascade.detectMultiScale2(face_roi,minNeighbors=10)
    for sx,sy,sw,sh in smile:
        cv2.rectangle(img2,(x+sx,y+sy),(x+sx+sw,sy+y+sh),(255,255,0),2)




cv2.imshow('friends',img2)
cv2.waitKey(0)
cv2.destroyAllWindows()